#!/usr/bin/env python3
"""Make GBA pointers inside generated byte arrays relocatable.

Some generated asset tables (map_rooms.c, event_backgrounds.c) describe
pointer-carrying structs as `const u8 NAME[N] = { bytes }`, so the pointers
are frozen GBA ROM addresses. For the Vita build this rewrites every such
array whose aligned words point inside a known ROM symbol into a u32 array
(bound to the original symbol name with an asm label) where those words are
address constants the linker relocates.

Usage: relocate_gen_c.py <in.c> <out.c> <gba.elf> <linked-symbols.txt>
"""

import bisect
import re
import struct
import subprocess
import sys

ARRAY_RE = re.compile(r"^const u8 (\w+)\[(\d+)\] = \{([^}]*)\};", re.M)


def load_symbols(elf, linked):
    out = subprocess.check_output(["arm-none-eabi-readelf", "-sW", elf], text=True)
    syms = {}
    for line in out.splitlines():
        parts = line.split()
        if len(parts) == 8 and parts[4] == "GLOBAL" and parts[3] != "FUNC" and parts[7] in linked:
            addr, size = int(parts[1], 16), int(parts[2])
            if 0x08000000 <= addr < 0x0A000000:
                syms[parts[7]] = (addr, size)
    ordered = sorted((a, s, n) for n, (a, s) in syms.items())
    return syms, ordered


def main():
    src, dst, elf, linked_path = sys.argv[1:5]
    linked = set(open(linked_path).read().split())
    syms, ordered = load_symbols(elf, linked)
    starts = [a for a, _, _ in ordered]
    text = open(src).read()
    refs = set()
    converted = 0

    def target(value):
        i = bisect.bisect_right(starts, value) - 1
        if i < 0:
            return None
        addr, size, name = ordered[i]
        # Assembly labels have no size: they extend to the next symbol.
        if size == 0 and i + 1 < len(ordered):
            size = ordered[i + 1][0] - addr
        # Past-the-end pointers are legal; anything further is not a pointer.
        if value - addr > size:
            return None
        return name, value - addr

    def rewrite(m):
        nonlocal converted
        name, count = m[1], int(m[2])
        data = bytes(int(x, 0) for x in m[3].replace("\n", " ").split(",") if x.strip())
        base = syms.get(name, (None,))[0]
        if base is None or base % 4 or count % 4 or len(data) != count:
            return m[0]
        words = []
        found = False
        for i in range(0, count, 4):
            w = struct.unpack_from("<I", data, i)[0]
            t = target(w) if 0x08000000 <= w < 0x0A000000 else None
            if t:
                refs.add(t[0])
                words.append(f"(u32)((const u8*){t[0]}__ref + 0x{t[1]:X})")
                found = True
            else:
                words.append(f"0x{w:08X}")
        if not found:
            return m[0]
        converted += 1
        body = ",\n    ".join(", ".join(words[j:j + 4]) for j in range(0, len(words), 4))
        # Keep the original identifier declared for later references in this file.
        return (f"extern const u8 {name}[{count}];\n"
                f"const u32 {name}__words[{count // 4}] __asm__(\"{name}\") __attribute__((aligned(4))) = {{\n"
                f"    {body}\n}};")

    out = ARRAY_RE.sub(rewrite, text)
    decls = "".join(f'extern const u8 {n}__ref[] __asm__("{n}");\n' for n in sorted(refs))
    marker = out.find("\n\n")
    out = out[:marker + 1] + "\n/* Relocation references added by tools/vita/relocate_gen_c.py. */\n" + decls + out[marker + 1:]
    open(dst, "w").write(out)
    print(f"{src}: {converted} arrays relocated, {len(refs)} symbols referenced")


if __name__ == "__main__":
    main()
